definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store

pipelines:
  pull-requests:
    "**":
      - step:
          name: Build and test
          image: node:22.12.0
          script:
            - corepack enable
            - corepack prepare pnpm@latest --activate
            - pnpm install
            - pnpm run lint
            - pnpm run test
          caches:
            - pnpm
