name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
     
      - name: Lint code
        run: pnpm lint

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

